/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import controller.Controller;
import javax.swing.table.DefaultTableModel;
import model.Customer;

/**
 *
 * @author Yasas Pasindu
 */
public class AllCustomerReports extends javax.swing.JFrame {

    /**
     * Creates new form BestInCustomer
     */
    public AllCustomerReports() {
        initComponents();
        setTitle("All Customer Reports");
        setLocationRelativeTo(null);
        tableData();
    }
    public void tableData(){
        String [] columnName={"Customer ID","XS","S","M","L","XL","XXL","Amount"};
        DefaultTableModel dtm = new DefaultTableModel(columnName,0);
        Customer [] tempar= Controller.allCustomerReports();
        		f:	for (int i = 0; i < tempar.length ; i++)
		{
			for (int k = 0; k < i; k++)
			{
				if (tempar[i].getPhoneNumber()==(tempar[k].getPhoneNumber()))
				{
					continue f;
				}
			}
			int xS=0;
			int s=0;
			int m=0;
			int l=0;
			int xL=0;
			int xXL=0;
			int totAmuont=0;
			
			for (int j = i; j < tempar.length; j++)
			{
					if (tempar[i].getPhoneNumber()==(tempar[j].getPhoneNumber()))
					{
						switch (tempar[j].getSize())
						{
                                                                case "XS":
                                                                xS+=tempar[j].getQty();
								break;
								case "S":
								s+=tempar[j].getQty();
                                                                System.out.println(tempar[j].getQty());
								break;
								case "M":
								m+=tempar[j].getQty();
								break;
								case "L":
								l+=tempar[j].getQty();
								break;
								case "XL":
								xL+=tempar[j].getQty();
								break;
								case "XXL":
								xXL+=tempar[j].getQty();
								break;
								
						}
						
						totAmuont+=tempar[j].getAmount();
					
					}
				
			}
			Object [] arr = {"0"+tempar[i].getPhoneNumber(),xS,s,m,l,xL,xXL,totAmuont+".00"};
                        dtm.addRow(arr);
			}
        
        table.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        placeBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        placeBack.setBackground(new java.awt.Color(0, 204, 153));
        placeBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        placeBack.setForeground(new java.awt.Color(255, 255, 255));
        placeBack.setText("Back");
        placeBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(placeBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(placeBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void placeBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeBackActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_placeBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllCustomerReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllCustomerReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllCustomerReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllCustomerReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllCustomerReports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton placeBack;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
