/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import FashionShop.*;
import controller.Controller;
import javax.swing.JOptionPane;
import model.Customer;

/**
 *
 * @author Yasas Pasindu
 */
public class ChangeOrderStatus extends javax.swing.JFrame {
    String temporyIdHolder;
    String temporyStatusHolder;
    Customer search;
    /**
     * Creates new form SearchCustomer
     */
    public ChangeOrderStatus() {
        initComponents();
        setTitle("Change Order Status");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Searchbutton = new javax.swing.JButton();
        placeBack = new javax.swing.JButton();
        textPhone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbAmount = new javax.swing.JLabel();
        lbIdQty = new javax.swing.JLabel();
        lbCusid = new javax.swing.JLabel();
        lbSize = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbStatus = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Searchbutton.setBackground(new java.awt.Color(0, 204, 153));
        Searchbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Searchbutton.setForeground(new java.awt.Color(255, 255, 255));
        Searchbutton.setText("Search");
        Searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Searchbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 42, -1, -1));

        placeBack.setBackground(new java.awt.Color(255, 0, 51));
        placeBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        placeBack.setForeground(new java.awt.Color(255, 255, 255));
        placeBack.setText("Back");
        placeBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeBackActionPerformed(evt);
            }
        });
        getContentPane().add(placeBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(textPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 140, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Enter Order ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel4.setText("Customer ID :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel5.setText("Size :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel6.setText("QTY :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel7.setText("Amount :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));
        getContentPane().add(lbAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 210, 30));
        getContentPane().add(lbIdQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 210, 30));
        getContentPane().add(lbCusid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 210, 30));
        getContentPane().add(lbSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 210, 30));

        jLabel1.setText("Status :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));
        getContentPane().add(lbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 200, 30));

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Change Status");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchbuttonActionPerformed
     String id = textPhone.getText();
      search = Controller.searchCustomer(id);
     
        try {
            lbCusid.setText(search.getPhoneNumber()+"");
            lbIdQty.setText(search.getQty()+"");
            lbAmount.setText(search.getAmount()+".00");
            lbSize.setText(search.getSize());
            lbStatus.setText(search.getStatus());
            temporyStatusHolder=search.getStatus();
            temporyIdHolder=id;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"invalid Input ");
        }
      
    }//GEN-LAST:event_SearchbuttonActionPerformed

    private void placeBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeBackActionPerformed
 
        this.dispose();
    }//GEN-LAST:event_placeBackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if (temporyStatusHolder.equals("processing")) {
             StatusPopup sp = new StatusPopup(search);
             sp.setVisible(true);
        }
        
        if (temporyStatusHolder.equals("Delivering")) {
            StatusPopup2 sp = new StatusPopup2(search);
            sp.setVisible(true);
        }
        } catch (Exception e) {
        }
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeOrderStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeOrderStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeOrderStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeOrderStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeOrderStatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Searchbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbAmount;
    private javax.swing.JLabel lbCusid;
    private javax.swing.JLabel lbIdQty;
    private javax.swing.JLabel lbSize;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JButton placeBack;
    private javax.swing.JTextField textPhone;
    // End of variables declaration//GEN-END:variables
}
