/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import controller.Controller;
import javax.swing.table.DefaultTableModel;
import model.Customer;


/**
 *
 * @author Yasas Pasindu
 */
public class ItemsByAmount extends javax.swing.JFrame {
       
    /**
     * Creates new form BestInCustomer
     */
    public ItemsByAmount() {
        initComponents();
        setTitle("Items By Amount");
        setLocationRelativeTo(null);
        tableData();
    }
    
    public void tableData(){
        String [] columnName={"Size","Qty","Total Amonut"};
        DefaultTableModel dtm = new DefaultTableModel(columnName,0);
        int priceList [] = {600,800,900,1000,1100,1200};
        Customer tempar[] = Controller.itemsByQty(); 
		int tempQty[]=new int [6];
		
		for (int i = 0; i <tempar.length ; i++)
		{
			switch (tempar[i].getSize())
			{
				case "XS":
					tempQty[0]+=tempar[i].getQty();
					break;
				case "S":
					tempQty[1]+=tempar[i].getQty();
					break;
					case "M":
					tempQty[2]+=tempar[i].getQty();
					break;
					case "L":
					tempQty[3]+=tempar[i].getQty();
					break;
					case "XL":
					tempQty[4]+=tempar[i].getQty();
					break;
					case "XXL":
					tempQty[5]=tempar[i].getQty();
					break;		
			}
			
		}
		int tempAmount[]=new int [6];
		for (int i = 0; i < tempAmount.length; i++)
		{
			tempAmount[i]=priceList[i]*tempQty[i];
		}
		String tempSize[] ={"XS","S","M","L","XL","XXL"};;
		boolean b=true;
		while(b){
			b=false;
		for (int i = 0; i < tempAmount.length-1 ; i++)
		{
			if ( tempQty[i]< tempQty[i+1])
			{
				b=true;
				int t =  tempAmount[i];
				 tempAmount [i] =  tempAmount[i+1];
				  tempAmount[i+1]=t;
				  t = tempQty[i];
				  tempQty[i]=tempQty[i+1];
				  tempQty[i+1]=t;
				  String s2 =  tempSize[i];
				   tempSize[i]= tempSize[i+1];
				    tempSize[i+1]=s2;
			}
		}
	}
        for (int i = 0; i < tempar.length; i++) {
            Object [] arr = {tempSize[i],tempQty[i],tempAmount[i]+".00"};
            dtm.addRow(arr);
        }
        
        table.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        placeBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        placeBack.setBackground(new java.awt.Color(0, 204, 153));
        placeBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        placeBack.setForeground(new java.awt.Color(255, 255, 255));
        placeBack.setText("Back");
        placeBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(placeBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(placeBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void placeBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeBackActionPerformed
       
        this.dispose();
    }//GEN-LAST:event_placeBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemsByAmount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemsByAmount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemsByAmount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemsByAmount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemsByAmount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton placeBack;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
