/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import View.MainMenu;
import controller.Controller;
import javax.swing.JOptionPane;
import model.Customer;

/**
 *
 * @author Yasas Pasindu
 */
public class PlaceOrder extends javax.swing.JFrame {

    static int ID;
    static String orderId;
    public static final int xs = 600;
    public static final int s = 800;
    public static final int m = 900;
    public static final int l = 1000;
    public static final int xl = 1100;
    public static final int xxl = 1200;

    public PlaceOrder() {

        initComponents();
        setTitle("Place Order");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    public void generateCode() {
        ID++;
        String id = String.format("ODR#%05d", ID);
        lbId.setText(id);
        orderId = id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        placeBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        placeBack1 = new javax.swing.JButton();
        textSize = new javax.swing.JTextField();
        textQty = new javax.swing.JTextField();
        textCusId = new javax.swing.JTextField();
        lbId = new javax.swing.JLabel();
        lbAmount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        placeBack.setBackground(new java.awt.Color(255, 51, 51));
        placeBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        placeBack.setForeground(new java.awt.Color(255, 255, 255));
        placeBack.setText("Back");
        placeBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeBackActionPerformed(evt);
            }
        });
        getContentPane().add(placeBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setText("Order ID :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 60, -1, -1));

        jLabel2.setText("Customer ID :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel3.setText("Size :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel4.setText("QTY :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel5.setText("Amount :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        placeBack1.setBackground(new java.awt.Color(0, 204, 153));
        placeBack1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        placeBack1.setForeground(new java.awt.Color(255, 255, 255));
        placeBack1.setText("Place Order");
        placeBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeBack1ActionPerformed(evt);
            }
        });
        getContentPane().add(placeBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, -1, -1));
        getContentPane().add(textSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 210, 30));

        textQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textQtyActionPerformed(evt);
            }
        });
        getContentPane().add(textQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 210, 30));

        textCusId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCusIdActionPerformed(evt);
            }
        });
        getContentPane().add(textCusId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 210, 30));
        getContentPane().add(lbId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 210, 30));
        getContentPane().add(lbAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 210, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void placeBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeBackActionPerformed
       
        this.dispose();
    }//GEN-LAST:event_placeBackActionPerformed

    private void placeBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeBack1ActionPerformed
        
        int amount = 0;
        int customerId = 0;
        String size = "";
        int qty = 0;
        try {
            customerId = Integer.parseInt(textCusId.getText().trim());
            if ((customerId + "").length() != 9) {
                JOptionPane.showMessageDialog(this, "Enter Vaild Phone Number");
                customerId = 0;
            }
            size = textSize.getText().trim();
            qty = Integer.parseInt(textQty.getText().trim());
            if (qty <= 0) {
                JOptionPane.showMessageDialog(this, "Enter Vaild Quantity");
               qty = 0;
            }

            if (size.equalsIgnoreCase("xs")) {
                amount = qty * xs;
            } else if (size.equalsIgnoreCase("s")) {
                amount = qty * s;
            } else if (size.equalsIgnoreCase("m")) {
                amount = qty * m;
            } else if (size.equalsIgnoreCase("l")) {
                amount = qty * l;
            } else if (size.equalsIgnoreCase("xl")) {
                amount = qty * xl;
            } else if (size.equalsIgnoreCase("xxl")) {
                amount = qty * xxl;
            } else {
                JOptionPane.showMessageDialog(this, "Wrong Input Size");
                size = "";
            }

        } catch (Exception e) {
        }

        if (!(amount == 0 || customerId == 0 || qty == 0 || size.equals(""))) {
            lbAmount.setText(amount + ".00");
            generateCode();
            Customer c = new Customer(orderId, customerId, size.toUpperCase(), amount, qty);
            boolean IsAdded = Controller.addCustomer(c);
            
            JOptionPane.showMessageDialog(this, "Order Successfully placed");
        } else {
            JOptionPane.showMessageDialog(this, "Order has not been placed");
        }
    }//GEN-LAST:event_placeBack1ActionPerformed

    private void textCusIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCusIdActionPerformed

    }//GEN-LAST:event_textCusIdActionPerformed

    private void textQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textQtyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaceOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbAmount;
    private javax.swing.JLabel lbId;
    private javax.swing.JButton placeBack;
    private javax.swing.JButton placeBack1;
    private javax.swing.JTextField textCusId;
    private javax.swing.JTextField textQty;
    private javax.swing.JTextField textSize;
    // End of variables declaration//GEN-END:variables
}
