/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Yasas Pasindu
 */
public class ViewReports extends javax.swing.JFrame {

    /**
     * Creates new form ViewReports
     */
    public ViewReports() {
        initComponents();
        setTitle("View Reports");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BestCusbtn = new javax.swing.JButton();
        AllCustomersbtn = new javax.swing.JButton();
        placeBack3 = new javax.swing.JButton();
        amountsortbtn = new javax.swing.JButton();
        ViewCustomers = new javax.swing.JButton();
        AllOrdersByAmount = new javax.swing.JButton();
        AllOrdersbtn = new javax.swing.JButton();
        placeBack8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BestCusbtn.setBackground(new java.awt.Color(0, 255, 0));
        BestCusbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BestCusbtn.setForeground(new java.awt.Color(255, 255, 255));
        BestCusbtn.setText("Best in Customers");
        BestCusbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BestCusbtnActionPerformed(evt);
            }
        });
        getContentPane().add(BestCusbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 134, -1, -1));

        AllCustomersbtn.setBackground(new java.awt.Color(0, 255, 0));
        AllCustomersbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AllCustomersbtn.setForeground(new java.awt.Color(255, 255, 255));
        AllCustomersbtn.setText("All Customers");
        AllCustomersbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllCustomersbtnActionPerformed(evt);
            }
        });
        getContentPane().add(AllCustomersbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 170, -1, -1));

        placeBack3.setBackground(new java.awt.Color(0, 0, 153));
        placeBack3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        placeBack3.setForeground(new java.awt.Color(255, 255, 255));
        placeBack3.setText("Categorized By Qty");
        placeBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeBack3ActionPerformed(evt);
            }
        });
        getContentPane().add(placeBack3, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 111, -1, -1));

        amountsortbtn.setBackground(new java.awt.Color(0, 0, 153));
        amountsortbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        amountsortbtn.setForeground(new java.awt.Color(255, 255, 255));
        amountsortbtn.setText("Categorized By Amount");
        amountsortbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountsortbtnActionPerformed(evt);
            }
        });
        getContentPane().add(amountsortbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 147, -1, -1));

        ViewCustomers.setBackground(new java.awt.Color(0, 255, 0));
        ViewCustomers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ViewCustomers.setForeground(new java.awt.Color(255, 255, 255));
        ViewCustomers.setText("View Customers");
        ViewCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewCustomersActionPerformed(evt);
            }
        });
        getContentPane().add(ViewCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 91, -1, -1));

        AllOrdersByAmount.setBackground(new java.awt.Color(153, 153, 153));
        AllOrdersByAmount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AllOrdersByAmount.setForeground(new java.awt.Color(255, 255, 255));
        AllOrdersByAmount.setText("Orders By Amount");
        AllOrdersByAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllOrdersByAmountActionPerformed(evt);
            }
        });
        getContentPane().add(AllOrdersByAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 111, -1, -1));

        AllOrdersbtn.setBackground(new java.awt.Color(153, 153, 153));
        AllOrdersbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AllOrdersbtn.setForeground(new java.awt.Color(255, 255, 255));
        AllOrdersbtn.setText("All Orders");
        AllOrdersbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllOrdersbtnActionPerformed(evt);
            }
        });
        getContentPane().add(AllOrdersbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 147, -1, -1));

        placeBack8.setBackground(new java.awt.Color(255, 51, 51));
        placeBack8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        placeBack8.setForeground(new java.awt.Color(255, 255, 255));
        placeBack8.setText("Back");
        placeBack8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeBack8ActionPerformed(evt);
            }
        });
        getContentPane().add(placeBack8, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BestCusbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BestCusbtnActionPerformed
        BestInCustomer bs = new BestInCustomer();
        bs.setVisible(true);
        
    }//GEN-LAST:event_BestCusbtnActionPerformed

    private void AllCustomersbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllCustomersbtnActionPerformed
      AllCustomerReports als = new AllCustomerReports();
      als.setVisible(true);
    }//GEN-LAST:event_AllCustomersbtnActionPerformed

    private void placeBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeBack3ActionPerformed
        ItemsByQty iq = new ItemsByQty();
        iq.setVisible(true);
        
    }//GEN-LAST:event_placeBack3ActionPerformed

    private void amountsortbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountsortbtnActionPerformed
        ItemsByAmount iba = new ItemsByAmount();
        iba.setVisible(true);
    }//GEN-LAST:event_amountsortbtnActionPerformed

    private void ViewCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewCustomersActionPerformed
        ViewCustomers vc = new ViewCustomers();
        vc.setVisible(true);
    }//GEN-LAST:event_ViewCustomersActionPerformed

    private void AllOrdersByAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllOrdersByAmountActionPerformed
        AllOrdersByAmount a = new AllOrdersByAmount();
        a.setVisible(true);
    }//GEN-LAST:event_AllOrdersByAmountActionPerformed

    private void AllOrdersbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllOrdersbtnActionPerformed
       AllOrders al = new AllOrders();
       al.setVisible(true);
    }//GEN-LAST:event_AllOrdersbtnActionPerformed

    private void placeBack8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeBack8ActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_placeBack8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewReports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AllCustomersbtn;
    private javax.swing.JButton AllOrdersByAmount;
    private javax.swing.JButton AllOrdersbtn;
    private javax.swing.JButton BestCusbtn;
    private javax.swing.JButton ViewCustomers;
    private javax.swing.JButton amountsortbtn;
    private javax.swing.JButton placeBack3;
    private javax.swing.JButton placeBack8;
    // End of variables declaration//GEN-END:variables
}
